version: '3.9'

services:
  gitlab:
    image: gitlab/gitlab-ce:18.4.5-ce.0
    container_name: gitlab
    restart: always
    hostname: 192.168.1.151
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.151'
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
        nginx['redirect_http_to_https'] = false
    ports:
      - "80:80"
      - "443:443"
      - "8822:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: '256m'
